### ISSUE TITLE
点开始修补,一直没进度

### ISSUE THREAD

**Issue by lls2wow** [affggh/Magisk_patcher#25]
- 检测到apk的magisk版本为 [b'27.0']
- 开始解压需要的文件...
- 解包boot镜像...
- 
然后没然后了

**Comment by lls2wow** [comment]
哦,python的报错内容是Traceback (most recent call last):
  File "C:\Users\linlv\anaconda3\envs\py11\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\linlv\anaconda3\envs\py11\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "d:\gitcode\Android_Pro\LSP_Relate\Magisk_patcher\mp\boot_patch.py", line 115, in patch
    err, ret = self.__execv(["unpack", bootimg])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\gitcode\Android_Pro\LSP_Relate\Magisk_patcher\mp\boot_patch.py", line 104, in __execv
    logging.info(ret.stdout.decode(encoding="utf-8"))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 110: invalid start byte

**Comment by lls2wow** [comment]
···
        # logging.info(ret.stdout.decode(encoding="utf-8", errors="ignore"))
        # return ret.returncode, ret.stdout.decode(encoding="utf-8")
        logging.info(ret.stdout)
        return ret.returncode, ret.stdout
··· 注释掉原本的decode后运行正常
