### ISSUE TITLE
alpha 支持不

### ISSUE THREAD

**Issue by wutaijieing** [affggh/Magisk_patcher#26]
卡在- 检测到apk的magisk版本为 [b'28.0']
- 开始解压需要的文件...
-

**Comment by ABC00012345** [comment]
same, and it throws error: Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.12/tkinter/__init__.py", line 1967, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/home/lukas/.local/lib/python3.12/site-packages/customtkinter/windows/widgets/ctk_button.py", line 554, in _clicked
    self._command()
  File "/home/lukas/Downloads/Magisk_patcher/mp/ui.py", line 401, in start_patch
    utils.parseMagiskApk(op.join("prebuilt", self.magisk_select_int.get()), arch=self.arch.get(), log=self)
  File "/home/lukas/Downloads/Magisk_patcher/mp/utils.py", line 199, in parseMagiskApk
    saveto(z.read(f"lib/{archto32(arch)}/libmagisk32.so"), "magisk32")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/zipfile/__init__.py", line 1567, in read
    with self.open(name, "r", pwd) as fp:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/zipfile/__init__.py", line 1604, in open
    zinfo = self.getinfo(name)
            ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/zipfile/__init__.py", line 1532, in getinfo
    raise KeyError(
KeyError: "There is no item named 'lib/armeabi-v7a/libmagisk32.so' in the archive"

**Comment by affggh** [comment]
28目前在网页版上尝试进行了支持
这个我其实不打算再更新了
你可以试试网页版的
https://circlecashteam.github.io/MagiskPatcher/
