### ISSUE TITLE
Works -- but not yet with Magisk v28 apk file

### ISSUE THREAD

**Issue by bnsmb** [affggh/Magisk_patcher#27]
[ OmniRom 14 Dev - xtrnaw7@t15g /data/develop/android/Magisk_patcher-4.1.0 ] $ Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib64/python3.12/tkinter/__init__.py", line 1968, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^```
^^
  File "/home/xtrnaw7/.local/lib/python3.12/site-packages/customtkinter/windows/widgets/ctk_button.py", line 554, in _clicked
    self._command()
  File "/data/develop/android/Magisk_patcher-4.1.0/mp/ui.py", line 396, in start_patch
    utils.parseMagiskApk(op.join("prebuilt", self.magisk_select_int.get()), arch=self.arch.get(), log=self)
  File "/data/develop/android/Magisk_patcher-4.1.0/mp/utils.py", line 194, in parseMagiskApk
    saveto(z.read(f"lib/{archto32(arch)}/libmagisk32.so"), "magisk32")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/zipfile/__init__.py", line 1567, in read
    with self.open(name, "r", pwd) as fp:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/zipfile/__init__.py", line 1604, in open
    zinfo = self.getinfo(name)
            ^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/zipfile/__init__.py", line 1532, in getinfo
    raise KeyError(
KeyError: "There is no item named 'lib/armeabi-v7a/libmagisk32.so' in the archive"
```
 
There is no libmagisk32.so in the archive for Magisk v28 anymore:


```
[ OmniRom 14 Dev - xtrnaw7@t15g /data/develop/android/Magisk_patcher-4.1.0/prebuilt ] $ unzip -t Magisk-v27.0.apk | grep lib/armeabi-v7a/libmagisk32.so 
    testing: lib/armeabi-v7a/libmagisk32.so   OK
[ OmniRom 14 Dev - xtrnaw7@t15g /data/develop/android/Magisk_patcher-4.1.0/prebuilt ] $ 

```
but : 

```
[ OmniRom 14 Dev - xtrnaw7@t15g /data/develop/android/Magisk_patcher-4.1.0/prebuilt ] $ unzip -t Magisk-v28.0.apk | grep lib/armeabi-v7a/libmagisk32.so 
[ OmniRom 14 Dev - xtrnaw7@t15g /data/develop/android/Magisk_patcher-4.1.0/prebuilt ] $ 
```

**Comment by misterwaztaken** [comment]
Just gonna point out your text and code snippets are reversed... (just had to point it out to you im sorry)

**Comment by bnsmb** [comment]
I don't understand what you're getting at ... the first unpack for Magisk v27 shows what it looks like for the Magisk version up to v27, and the next unpack is supposed to show what it looks like for Magisk v28

**Comment by affggh** [comment]
try this web one
https://circlecashteam.github.io/MagiskPatcher/

**Comment by bnsmb** [comment]
The Web versions successfully creates a boot  image with Magisk v28.0

<details><summary><b>Magisk Patcher Output</b></summary>

Magisk Patcher on WEB
Author: affggh
Version: 0.1.2

Info: Upload boot image.
Info: Handle uploaded boot image...
Success: Success upload file
Info: Upload magisk apk.
Info: Handle uploaded apk file...
Success: Success upload file
Info: Get Magisk version code: 28000
Info: Loaded needed: init-ld
Info: Loaded needed: stub.apk
Info: Loaded needed: magiskinit
Info: Loaded needed: magisk
Info: Setup environment key: KEEPVERITY value: true
Info: Setup environment key: KEEPFORCEENCRYPT value: true
Info: Setup environment key: PATCHVBMETAFLAG value: false
Info: Setup environment key: RECOVERYMODE value: false
Info: Setup environment key: LEGACYSAR value: false
Info: Chdir: /home/web_user
Info: Write boot image into emscripiten FS: /home/web_user/boot.img
Info: Write file into emscripten FS: init-ld -> /home/web_user/init-ld
Info: Write file into emscripten FS: stub.apk -> /home/web_user/stub.apk
Info: Write file into emscripten FS: magiskinit -> /home/web_user/magiskinit
Info: Write file into emscripten FS: magisk -> /home/web_user/magisk
Info: - Unpacking boot image
Parsing boot image: [boot.img]
HEADER_VER      [4]
KERNEL_SZ       [39909888]
RAMDISK_SZ      [1663223]
OS_VERSION      [13.0.0]
OS_PATCH_LEVEL  [2025-01]
PAGESIZE        [4096]
CMDLINE         []
KERNEL_FMT      [raw]
RAMDISK_FMT     [lz4_legacy]
unexpected ASN.1 DER tag: expected SEQUENCE, got APPLICATION [1] (primitive)
VBMETA
Info: - Checking ramdisk status
Loading cpio: [ramdisk.cpio]
Info: - Stock boot image detected
Info: - Patching ramdisk
Info: Compress magisk info xz...
Info: Compress stub.apk info xz...
Info: Compress init-ld info xz...
Loading cpio: [ramdisk.cpio]
Add file [init] (100750)
Create directory [overlay.d] (0750)
Create directory [overlay.d/sbin] (0750)
Add file [overlay.d/sbin/magisk.xz] (100644)
Add file [overlay.d/sbin/stub.apk.xz] (100644)
Add file [overlay.d/sbin/init-ld.xz] (100644)
Patch with flag KEEPVERITY=[true] KEEPFORCEENCRYPT=[true]
Loading cpio: [ramdisk.cpio.orig]
Backup [init] -> [.backup/init.xz]
Record new entry: [overlay.d] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin/init-ld.xz] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin/magisk.xz] -> [.backup/.rmlist]
Record new entry: [overlay.d/sbin/stub.apk.xz] -> [.backup/.rmlist]
Create directory [.backup] (0000)
Add file [.backup/.magisk] (100000)
Dumping cpio: [ramdisk.cpio]
Parsing boot image: [boot.img]
HEADER_VER      [4]
KERNEL_SZ       [39909888]
RAMDISK_SZ      [1663223]
OS_VERSION      [13.0.0]
OS_PATCH_LEVEL  [2025-01]
PAGESIZE        [4096]
CMDLINE         []
KERNEL_FMT      [raw]
RAMDISK_FMT     [lz4_legacy]
unexpected ASN.1 DER tag: expected SEQUENCE, got APPLICATION [1] (primitive)
VBMETA
Repack to boot image: [new-boot.img]
HEADER_VER      [4]
KERNEL_SZ       [39909888]
RAMDISK_SZ      [1340971]
OS_VERSION      [13.0.0]
OS_PATCH_LEVEL  [2025-01]
PAGESIZE        [4096]
CMDLINE         []
Success: Worker terminated.
Success: Download starting...

</details>

But the Magisk App fails to start and is automatically deinstalled by Android : 

 **Installing the Magisk App**

```
[xtrnaw7@t15g ~/Downloads]$ adb shell logcat | grep topjohn
03-20 09:43:29.929  1449  1449 E ActivityManager: Unable to find com.topjohnwu.magisk/u0


03-20 09:44:07.873  1449  1703 W ziparchive: Unable to open '/data/app/~~QP0OPOx1pc46nweeNR_hug==/com.topjohnwu.magisk-y3SYZZlHNDhUkgfZr712Nw==/base.dm': No such file or directory
03-20 09:44:07.874  1449  1703 I PackageDexOptimizer: Running dexopt (dexoptNeeded=1) on: /data/app/~~QP0OPOx1pc46nweeNR_hug==/com.topjohnwu.magisk-y3SYZZlHNDhUkgfZr712Nw==/base.apk pkg=com.topjohnwu.magisk isa=arm dexoptFlags=boot_complete,profile_guided,public,enable_hidden_api_checks targetFilter=speed-profile oatDir=/data/app/~~QP0OPOx1pc46nweeNR_hug==/com.topjohnwu.magisk-y3SYZZlHNDhUkgfZr712Nw==/oat classLoaderContext=PCL[]{}
03-20 09:44:07.874  1277  1299 V installd: DexInv: --- BEGIN '/data/app/~~QP0OPOx1pc46nweeNR_hug==/com.topjohnwu.magisk-y3SYZZlHNDhUkgfZr712Nw==/base.apk' ---
03-20 09:44:07.874  1277  1299 V installd: Running /apex/com.android.art/bin/dex2oat32 in=base.apk out=/data/app/~~QP0OPOx1pc46nweeNR_hug==/com.topjohnwu.magisk-y3SYZZlHNDhUkgfZr712Nw==/oat/arm/base.odex
03-20 09:44:07.927  4869  4869 I dex2oat32: /apex/com.android.art/bin/dex2oat32 --input-vdex-fd=-1 --output-vdex-fd=10 --classpath-dir=/data/app/~~QP0OPOx1pc46nweeNR_hug==/com.topjohnwu.magisk-y3SYZZlHNDhUkgfZr712Nw== --class-loader-context=PCL[]{} --compact-dex-level=none --compiler-filter=speed-profile --compilation-reason=install --max-image-block-size=524288 --resolve-startup-const-strings=true --generate-mini-debug-info
03-20 09:44:08.129  1277  1299 V installd: DexInv: --- END '/data/app/~~QP0OPOx1pc46nweeNR_hug==/com.topjohnwu.magisk-y3SYZZlHNDhUkgfZr712Nw==/base.apk' (success) ---
03-20 09:44:08.139  1449  1703 W ziparchive: Unable to open '/data/app/~~QP0OPOx1pc46nweeNR_hug==/com.topjohnwu.magisk-y3SYZZlHNDhUkgfZr712Nw==/base.dm': No such file or directory
03-20 09:44:08.139  1449  1703 I PackageDexOptimizer: Running dexopt (dexoptNeeded=1) on: /data/app/~~QP0OPOx1pc46nweeNR_hug==/com.topjohnwu.magisk-y3SYZZlHNDhUkgfZr712Nw==/base.apk pkg=com.topjohnwu.magisk isa=arm64 dexoptFlags=boot_complete,profile_guided,public,enable_hidden_api_checks targetFilter=speed-profile oatDir=/data/app/~~QP0OPOx1pc46nweeNR_hug==/com.topjohnwu.magisk-y3SYZZlHNDhUkgfZr712Nw==/oat classLoaderContext=PCL[]{}
03-20 09:44:08.140  1277  1299 V installd: DexInv: --- BEGIN '/data/app/~~QP0OPOx1pc46nweeNR_hug==/com.topjohnwu.magisk-y3SYZZlHNDhUkgfZr712Nw==/base.apk' ---
03-20 09:44:08.140  1277  1299 V installd: Running /apex/com.android.art/bin/dex2oat32 in=base.apk out=/data/app/~~QP0OPOx1pc46nweeNR_hug==/com.topjohnwu.magisk-y3SYZZlHNDhUkgfZr712Nw==/oat/arm64/base.odex
03-20 09:44:08.185  4879  4879 I dex2oat32: /apex/com.android.art/bin/dex2oat32 --input-vdex-fd=-1 --output-vdex-fd=10 --classpath-dir=/data/app/~~QP0OPOx1pc46nweeNR_hug==/com.topjohnwu.magisk-y3SYZZlHNDhUkgfZr712Nw== --class-loader-context=PCL[]{} --compact-dex-level=none --compiler-filter=speed-profile --compilation-reason=install --max-image-block-size=524288 --resolve-startup-const-strings=true --generate-mini-debug-info
03-20 09:44:08.382  1277  1299 V installd: DexInv: --- END '/data/app/~~QP0OPOx1pc46nweeNR_hug==/com.topjohnwu.magisk-y3SYZZlHNDhUkgfZr712Nw==/base.apk' (success) ---
03-20 09:44:08.392  1449  1703 V BackupManagerService: [UserID:0] restoreAtInstall pkg=com.topjohnwu.magisk token=1 restoreSet=0
03-20 09:44:08.399  3357  3357 I MediaProvider: Invalidating LocalCallingIdentity cache for package com.topjohnwu.magisk. Reason: package android.intent.action.PACKAGE_ADDED
03-20 09:44:08.415  2620  2620 D MediaPlayerList: Name of package changed: com.topjohnwu.magisk
03-20 09:44:08.424  2504  2541 D SessionCommitReceiver: Adding package name to install queue. Package name: com.topjohnwu.magisk, has app icon: false, has app label: false
03-20 09:44:08.425  2620  2620 D MediaPlayerList: Name of package changed: com.topjohnwu.magisk
03-20 09:44:08.431  2504  2541 D ItemInstallQueue: Adding PendingInstallShortcutInfo to queue. Attached info: WorkspaceItemInfo(id=-1 type=APP container=# com.android.launcher3.logger.LauncherAtom$ContainerInfo@7bc6f targetComponent=ComponentInfo{com.topjohnwu.magisk/com.topjohnwu.magisk.ui.MainActivity} screen=-1 cell(-1,-1) span(1,1) minSpan(1,1) rank=0 user=UserHandle{0} title=Magisk)
03-20 09:44:08.433  2763  2763 D CarrierSvcBindHelper: onPackageAdded: com.topjohnwu.magisk
03-20 09:44:08.446  1449  3356 W BackupTransportManager: Package com.topjohnwu.magisk enabled setting: 0
03-20 09:44:08.447  2504  2541 D AddWorkspaceItemsTask: } targetComponent=ComponentInfo{com.topjohnwu.magisk/com.topjohnwu.magisk.ui.MainActivity} screen=1 cell(2,3) span(1,1) minSpan(1,1) rank=0 user=UserHandle{0} title=Magisk)
03-20 09:44:08.451  2763  2763 D CarrierSvcBindHelper: onPackageModified: com.topjohnwu.magisk
03-20 09:44:08.451  2763  2763 D ImsResolver: maybeAddedImsService, packageName: com.topjohnwu.magisk
03-20 09:44:08.466  2763  2763 D ImsResolver: maybeAddedImsService, packageName: com.topjohnwu.magisk

```

**Starting the Magisk App**

```
03-20 09:44:25.041  1449  1969 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.topjohnwu.magisk/.ui.MainActivity bnds=[540,1044][788,1338]} from uid 10177
03-20 09:44:25.070  1449  4802 D CoreBackPreview: Window{789d76a u0 Splash Screen com.topjohnwu.magisk}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@46d4dd1, mPriority=0}
03-20 09:44:25.073  1449  1662 I ActivityManager: Start proc 4922:com.topjohnwu.magisk/u0a201 for next-top-activity {com.topjohnwu.magisk/com.topjohnwu.magisk.ui.MainActivity}
03-20 09:44:25.107  4922  4922 V GraphicsEnvironment: ANGLE Developer option for 'com.topjohnwu.magisk' set to: 'default'
03-20 09:44:25.107  4922  4922 V GraphicsEnvironment: ANGLE GameManagerService for com.topjohnwu.magisk: false
03-20 09:44:25.141  4922  4942 D ProfileInstaller: Installing profile for com.topjohnwu.magisk
03-20 09:44:25.145   801   803 E Magisk  : pkg: APK signature mismatch: /data/app/~~QP0OPOx1pc46nweeNR_hug==/com.topjohnwu.magisk-y3SYZZlHNDhUkgfZr712Nw==/base.apk
03-20 09:44:25.170  4957  4957 I Magisk  : pm_uninstall: com.topjohnwu.magisk
03-20 09:44:25.175  1449  1969 D CoreBackPreview: Window{d6bf840 u0 com.topjohnwu.magisk/com.topjohnwu.magisk.ui.MainActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@fb68be, mPriority=0}
03-20 09:44:25.214  1449  1660 I ActivityManager: Force stopping com.topjohnwu.magisk appid=10201 user=-1: deletePackageX
03-20 09:44:25.218  1449  1660 I ActivityManager: Killing 4922:com.topjohnwu.magisk/u0a201 (adj 0): stop com.topjohnwu.magisk due to deletePackageX
03-20 09:44:25.223  1449  1660 W ActivityTaskManager: Force removing ActivityRecord{2b6e35e u0 com.topjohnwu.magisk/.ui.MainActivity} t17 f}}: app died, no saved state
03-20 09:44:25.228  1449  1522 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(uid/pid:10201/4922, [NetworkRequest [ LISTEN id=74, [ Capabilities: NOT_RESTRICTED&TRUSTED&NOT_VPN&VALIDATED&FOREGROUND&NOT_VCN_MANAGED Uid: 10201 RequestorUid: 10201 RequestorPkg: com.topjohnwu.magisk UnderlyingNetworks: Null] ]], android.os.BinderProxy@8dd7eed)
03-20 09:44:25.282  1449  2006 I WindowManager: WIN DEATH: Window{d6bf840 u0 com.topjohnwu.magisk/com.topjohnwu.magisk.ui.MainActivity}
03-20 09:44:25.282  1449  2006 W InputManager-JNI: Input channel object 'd6bf840 com.topjohnwu.magisk/com.topjohnwu.magisk.ui.MainActivity (client)' was disposed without first being removed with the input manager!
03-20 09:44:25.299  1449  2049 V ActivityManager: Got obituary of 4922:com.topjohnwu.magisk
03-20 09:44:25.317  1449  1703 I ActivityManager: Force stopping com.topjohnwu.magisk appid=10201 user=0: pkg removed
03-20 09:44:25.318  1449  1703 I WindowManager:   Force removing ActivityRecord{2b6e35e u0 com.topjohnwu.magisk/.ui.MainActivity} t17 f} isExiting}
03-20 09:44:25.318  1449  1703 W WindowManager: removeAppToken: Attempted to remove non-existing token: Token{444a499 ActivityRecord{2b6e35e u0 com.topjohnwu.magisk/.ui.MainActivity} t17 f} isExiting}}
03-20 09:44:25.348  3357  3357 I MediaProvider: Invalidating LocalCallingIdentity cache for package com.topjohnwu.magisk. Reason: package android.intent.action.PACKAGE_REMOVED
03-20 09:44:25.363  1449  2007 W WifiService: Couldn't get PackageInfo for package:com.topjohnwu.magisk
03-20 09:44:25.366  1449  2007 D WifiService: Remove settings for package:com.topjohnwu.magisk
03-20 09:44:25.366  1449  2007 D WifiConfigManager: Remove all networks for app ApplicationInfo{2aee7d0 com.topjohnwu.magisk}
03-20 09:44:25.366  1449  1968 V StorageManagerService: Package com.topjohnwu.magisk does not have legacy storage
03-20 09:44:25.367  1449  1907 I RollbackManager: broadcast=ACTION_PACKAGE_FULLY_REMOVED pkg=com.topjohnwu.magisk
03-20 09:44:25.370  1449  2007 I PasspointManager: No app ops listener found for com.topjohnwu.magisk
03-20 09:44:25.370  1449  2007 W WifiService: Couldn't get PackageInfo for package:com.topjohnwu.magisk
03-20 09:44:25.370  1449  2007 D WifiService: Remove settings for package:com.topjohnwu.magisk
03-20 09:44:25.370  1449  2007 D WifiConfigManager: Remove all networks for app ApplicationInfo{5c645da com.topjohnwu.magisk}
03-20 09:44:25.392  1449  1449 I GameManagerService: Disabling downscale for com.topjohnwu.magisk
03-20 09:44:25.401  1449  2007 I PasspointManager: No app ops listener found for com.topjohnwu.magisk
03-20 09:44:25.401  1449  1449 I Telecom : CarModeTracker: Package com.topjohnwu.magisk is not tracked.: SSH.oR@AI8
03-20 09:44:25.403  1449  1449 I ConditionProviders: Disallowing condition provider com.topjohnwu.magisk (userSet: true)
03-20 09:44:25.424  2763  2763 D CarrierSvcBindHelper: onPackageRemoved: com.topjohnwu.magisk
03-20 09:44:25.485  2504  2504 D Launcher.Model: package removed received com.topjohnwu.magisk
03-20 09:44:25.486  2504  2541 D PackageUpdatedTask: Removing app iconcom.topjohnwu.magisk
03-20 09:44:25.488  2504  2541 D ModelWriter: removing items from db com.topjohnwu.magisk. Reason: [removed because the corresponding package or component is removed. mOp=3 removedPackages=[com.topjohnwu.magisk] removedComponents=[]]
03-20 09:44:25.586  1449  2987 D CoreBackPreview: Window{789d76a u0 Splash Screen com.topjohnwu.magisk EXITING}: Setting back callback null
03-20 09:44:25.586  1449  2987 W InputManager-JNI: Input channel object '789d76a Splash Screen com.topjohnwu.magisk (client)' was disposed without first being removed with the input manager!
03-20 09:44:25.591  4509  4509 D GmsGcmUnregisterRcvr: Package removed or data cleared: com.topjohnwu.magisk
03-20 09:44:25.591  3357  4048 D MediaProvider: Deleted 0 Android/media items belonging to com.topjohnwu.magisk on /data/user/0/com.android.providers.media.module/databases/external.db



^C
[xtrnaw7@t15g ~/Downloads]$ 
```

The error is the same for Magisk 28.1 ; the installation works with Magisk 27.0

**Comment by ABC00012345** [comment]
same here, the web version works but magisk doesnt detect root, but su command works
