### ISSUE TITLE
win10修补时卡79%

### ISSUE THREAD

**Issue by QingJ01** [affggh/Magisk_patcher#7]
日志如下
- Unpacking boot image
- Checking ramdisk status
- Stock boot image detected
Exception in thread Thread-11 (__Patch):
Traceback (most recent call last):
  File "C:\Users\86156\AppData\Local\Temp\ONEFIL~2\threading.py", line 1016, in _bootstrap_inner
  File "C:\Users\86156\AppData\Local\Temp\ONEFIL~2\threading.py", line 953, in run
  File "C:\Users\86156\AppData\Local\Temp\ONEFIL~2\Magiskpatcher.py", line 350, in __Patch
    p.patchboot(self.filename.get())
  File "C:\Users\86156\AppData\Local\Temp\ONEFIL~2\pyscripts\boot_patch.py", line 123, in patchboot
  File "C:\Users\86156\AppData\Local\Temp\ONEFIL~2\shutil.py", line 254, in copyfile
FileNotFoundError: [Errno 2] No such file or directory: 'ramdisk.cpio'
Exception in threading.excepthook:
Exception ignored in thread started by: <bound method Thread._bootstrap of <Thread(Thread-11 (__Patch), started daemon 15940)>>
Traceback (most recent call last):
  File "C:\Users\86156\AppData\Local\Temp\ONEFIL~2\threading.py", line 973, in _bootstrap
  File "C:\Users\86156\AppData\Local\Temp\ONEFIL~2\threading.py", line 1018, in _bootstrap_inner
  File "C:\Users\86156\AppData\Local\Temp\ONEFIL~2\threading.py", line 1336, in invoke_excepthook
AttributeError: 'myStdout' object has no attribute 'flush'
Exception ignored in sys.unraisablehook: <built-in function unraisablehook>
AttributeError: 'myStdout' object has no attribute 'flush'

**Comment by affggh** [comment]
你这个boot镜像没有ramdisk导致的报错，我记得我修好了怎么还报错捏

**Comment by QingJ01** [comment]
砖了怎么办，大佬能给个联系方式帮我有偿修复一下吗

**Comment by affggh** [comment]
> 砖了怎么办，大佬能给个联系方式帮我有偿修复一下吗

自己修吧🐰
