### ISSUE TITLE
修补时报错

### ISSUE THREAD

**Issue by xxroot** [affggh/Magisk_patcher#8]
Parse Magisk Version : 24.3

Exception in thread Thread-7:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "D:\桌面\Magisk_patcher-ttkbootstrap\Magiskpatcher.py", line 340, in __Patch
    if not self.__parseApk():
  File "D:\桌面\Magisk_patcher-ttkbootstrap\Magiskpatcher.py", line 321, in __parseApk
    shutil.move("tmp/assets/", "assets/")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 821, in move
    raise Error("Destination path '%s' already exists" % real_dst)
shutil.Error: Destination path 'assets/assets' already exists
Exception in threading.excepthook:
Exception ignored in thread started by: <bound method Thread._bootstrap of <Thread(Thread-7, started daemon 14812)>>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\threading.py", line 930, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\threading.py", line 975, in _bootstrap_inner
    self._invoke_excepthook(self)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\threading.py", line 1257, in invoke_excepthook
    local_print("Exception in threading.excepthook:",
AttributeError: 'myStdout' object has no attribute 'flush'
Exception ignored in sys.unraisablehook: <built-in function unraisablehook>
AttributeError: 'myStdout' object has no attribute 'flush'

**Comment by affggh** [comment]
你是不是改了什么，不支持低于22.1以下的版本
或者重新下载官方的apk包，手动放进prebuilt目录里

**Comment by xxroot** [comment]
解决了，是我电脑环境的问题，谢谢大佬

**Comment by affggh** [comment]
> 解决了，是我电脑环境的问题，谢谢大佬

好的，那没有问题我就关闭这个issue了

**Comment by lbenw126** [comment]
请问怎么解决的，我也有这个问题
